export const OCR_DERIVED_ARTIFACT_VERSION = "m4.4-derived-v2";

export const OCR_NORMALIZED_PAGES_SCHEMA_VERSION = 2;
export const OCR_IMAGE_MANIFEST_SCHEMA_VERSION = 2;
export const OCR_ARTIFACT_AUDIT_SCHEMA_VERSION = 1;
