import { Inject, Injectable } from "@nestjs/common";
import {
  InMemoryCache,
  fetchTranscript,
  listLanguages,
  type CaptionTrackInfo,
  type TranscriptSegment,
} from "youtube-transcript-plus";
import {
  throwBadRequest,
  throwNotFound,
  throwServiceUnavailable,
} from "#api/common/errors/api-exception";
import { PrismaService } from "#api/common/prisma/prisma.service";

const YOUTUBE_REQUEST_TIMEOUT_MS = 12_000;
const YOUTUBE_CACHE_TTL_MS = 5 * 60 * 1000;
const MAX_TRANSCRIPT_SEGMENTS = 10_000;
const DEFAULT_START_TIME_IN_SECONDS = 5;
const DEFAULT_END_TIME_CUT_IN_SECONDS = 22;

const youtubeCache = new InMemoryCache(YOUTUBE_CACHE_TTL_MS);

export type VideoTranscriptSegment = {
  endTime?: number;
  time: number;
  text: string;
};

export type VideoTranscriptChapter = {
  time: number;
  title: string;
};

export type YoutubeTranscriptResult = {
  timeline: "SOURCE";
  language: string;
  languageLabel: string;
  isAutoGenerated: boolean;
  videoDuration: number;
  playbackStartTime: number;
  playbackEndTime: number;
  chapters: VideoTranscriptChapter[];
  segments: VideoTranscriptSegment[];
};

export type VideoPlaybackWindow = {
  startTime: number;
  endTime: number;
};

@Injectable()
export class YoutubeTranscriptService {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}

  async fetchForLesson(lessonId: string): Promise<YoutubeTranscriptResult> {
    const lesson = await this.prisma.lesson.findFirst({
      where: {
        id: lessonId,
        deletedAt: null,
      },
      select: {
        customVideoSettings: true,
        videoUrl: true,
      },
    });

    if (!lesson) {
      throwNotFound("LESSON_NOT_FOUND", "Không tìm thấy buổi học");
    }

    const videoId = extractYoutubeVideoId(lesson.videoUrl);
    if (!videoId) {
      throwBadRequest(
        "VIDEO_TRANSCRIPT_UNSUPPORTED",
        "Chỉ có thể lấy transcript cho video YouTube",
      );
    }

    try {
      const languages = await listLanguages(videoId, createTranscriptConfig());
      const selectedLanguage = selectCaptionLanguage(languages);
      if (!selectedLanguage) {
        return throwNotFound(
          "VIDEO_TRANSCRIPT_NOT_AVAILABLE",
          "Video này không có bản chép lời công khai",
        );
      }

      const transcriptResult = await fetchTranscript(videoId, {
        ...createTranscriptConfig(),
        lang: selectedLanguage.languageCode,
        videoDetails: true,
      });
      const playbackWindow = resolveVideoPlaybackWindow(
        lesson.customVideoSettings,
        transcriptResult.videoDetails.lengthSeconds,
      );
      if (!playbackWindow) {
        return throwBadRequest(
          "VIDEO_TRANSCRIPT_INVALID_WINDOW",
          "Khoảng phát video sau khi cắt đầu/cuối không hợp lệ",
        );
      }
      const chapters = readVideoChapters(lesson.customVideoSettings);
      const segments = normalizeTranscriptSegments(transcriptResult.segments);

      return {
        timeline: "SOURCE",
        language: selectedLanguage.languageCode,
        languageLabel: selectedLanguage.languageName,
        isAutoGenerated: selectedLanguage.isAutoGenerated,
        videoDuration: transcriptResult.videoDetails.lengthSeconds,
        playbackStartTime: playbackWindow.startTime,
        playbackEndTime: playbackWindow.endTime,
        chapters,
        segments,
      };
    } catch (error) {
      if (isHttpException(error)) {
        throw error;
      }

      const errorName = getErrorName(error);
      if (
        errorName === "YoutubeTranscriptDisabledError" ||
        errorName === "YoutubeTranscriptNotAvailableError" ||
        errorName === "YoutubeTranscriptNotAvailableLanguageError" ||
        errorName === "YoutubeTranscriptVideoUnavailableError"
      ) {
        return throwNotFound(
          "VIDEO_TRANSCRIPT_NOT_AVAILABLE",
          "Video này không có bản chép lời công khai",
        );
      }

      if (errorName === "YoutubeTranscriptInvalidVideoIdError") {
        return throwBadRequest(
          "VIDEO_TRANSCRIPT_UNSUPPORTED",
          "Link video YouTube không hợp lệ",
        );
      }

      if (errorName === "YoutubeTranscriptTooManyRequestError") {
        return throwServiceUnavailable(
          "VIDEO_TRANSCRIPT_RATE_LIMITED",
          "YouTube đang giới hạn yêu cầu. Vui lòng thử lại sau",
        );
      }

      return throwServiceUnavailable(
        "VIDEO_TRANSCRIPT_UPSTREAM_ERROR",
        "YouTube chưa trả được bản chép lời. Vui lòng thử lại sau",
      );
    }
  }
}

export function extractYoutubeVideoId(videoUrl: string | null | undefined) {
  if (!videoUrl) {
    return null;
  }

  try {
    const url = new URL(videoUrl);
    const hostname = url.hostname.replace(/^www\./, "").toLowerCase();
    if (hostname === "youtu.be") {
      const id = url.pathname.split("/").filter(Boolean)[0];
      return isYoutubeVideoId(id) ? id : null;
    }

    if (hostname === "youtube.com" || hostname.endsWith(".youtube.com")) {
      const pathParts = url.pathname.split("/").filter(Boolean);
      const id =
        url.pathname === "/watch"
          ? url.searchParams.get("v")
          : pathParts[0] === "embed" || pathParts[0] === "shorts"
            ? pathParts[1]
            : null;
      return isYoutubeVideoId(id) ? id : null;
    }
  } catch {
    return null;
  }

  return null;
}

export function normalizeTranscriptSegments(
  transcript: TranscriptSegment[],
  playbackWindow?: VideoPlaybackWindow,
): VideoTranscriptSegment[] {
  const sourceSegments: Array<TranscriptSegment & { text: string }> = [];
  const sortedTranscript = [...transcript].sort(
    (first, second) => first.offset - second.offset,
  );

  for (const segment of sortedTranscript) {
    const text = segment.text.replace(/\s+/g, " ").trim();
    if (!text || !Number.isFinite(segment.offset) || segment.offset < 0) {
      continue;
    }
    if (
      playbackWindow &&
      (segment.offset < playbackWindow.startTime ||
        segment.offset >= playbackWindow.endTime)
    ) {
      continue;
    }

    const previous = sourceSegments.at(-1);
    if (previous?.text === text) {
      continue;
    }

    sourceSegments.push({
      ...segment,
      duration: playbackWindow
        ? Math.min(
            Math.max(0, segment.duration),
            Math.max(0, playbackWindow.endTime - segment.offset),
          )
        : segment.duration,
      offset: playbackWindow
        ? Math.max(0, segment.offset - playbackWindow.startTime)
        : segment.offset,
      text,
    });
  }

  return toTimestampedTranscriptSegments(sourceSegments).slice(
    0,
    MAX_TRANSCRIPT_SEGMENTS,
  );
}

export function toTimestampedTranscriptSegments(
  transcript: TranscriptSegment[],
): VideoTranscriptSegment[] {
  return [...transcript]
    .sort((first, second) => first.offset - second.offset)
    .flatMap((segment) => {
      const text = segment.text.replace(/\s+/g, " ").trim();
      if (!text || !Number.isFinite(segment.offset) || segment.offset < 0) {
        return [];
      }

      const duration =
        Number.isFinite(segment.duration) && segment.duration > 0 ? segment.duration : 0;
      return [
        {
          endTime: roundTranscriptTime(segment.offset + duration),
          time: roundTranscriptTime(segment.offset),
          text,
        },
      ];
    });
}

export function resolveVideoPlaybackWindow(
  settings: unknown,
  videoDuration: number,
): VideoPlaybackWindow | null {
  if (!Number.isFinite(videoDuration) || videoDuration <= 0) {
    return null;
  }

  const settingsRecord = toSettingsRecord(settings);
  if (settingsRecord?.isDisabled === true) {
    return {
      startTime: 0,
      endTime: videoDuration,
    };
  }

  const startTime = readNonNegativeNumber(
    settingsRecord?.startTimeInSeconds,
    DEFAULT_START_TIME_IN_SECONDS,
  );
  const endTimeCut = readNonNegativeNumber(
    settingsRecord?.endTimeCutInSeconds,
    DEFAULT_END_TIME_CUT_IN_SECONDS,
  );
  const endTime = Math.min(videoDuration, videoDuration - endTimeCut);

  if (endTime <= startTime) {
    return null;
  }

  return {
    startTime,
    endTime,
  };
}

export function readVideoChapters(settings: unknown): VideoTranscriptChapter[] {
  const settingsRecord = toSettingsRecord(settings);
  if (!Array.isArray(settingsRecord?.chapters)) {
    return [];
  }

  return settingsRecord.chapters
    .flatMap((chapter) => {
      const record = toSettingsRecord(chapter);
      const time = record?.time;
      const title = record?.title;
      return typeof time === "number" &&
        Number.isFinite(time) &&
        time >= 0 &&
        typeof title === "string" &&
        title.trim().length > 0
        ? [{ time, title: title.trim() }]
        : [];
    })
    .sort((first, second) => first.time - second.time);
}

export function getPlaybackChapters(
  chapters: VideoTranscriptChapter[],
  playbackWindow: VideoPlaybackWindow,
) {
  const sortedChapters = [...chapters].sort((first, second) => first.time - second.time);
  const chapterAtPlaybackStart = sortedChapters
    .filter((chapter) => chapter.time <= playbackWindow.startTime)
    .at(-1);
  const chaptersInsideWindow = sortedChapters.filter(
    (chapter) =>
      chapter.time > playbackWindow.startTime && chapter.time < playbackWindow.endTime,
  );

  return [
    ...(chapterAtPlaybackStart ? [{ ...chapterAtPlaybackStart, time: 0 }] : []),
    ...chaptersInsideWindow.map((chapter) => ({
      ...chapter,
      time: roundTranscriptTime(chapter.time - playbackWindow.startTime),
    })),
  ];
}

function createTranscriptConfig() {
  return {
    cache: youtubeCache,
    cacheTTL: YOUTUBE_CACHE_TTL_MS,
    retries: 1,
    retryDelay: 250,
    signal: AbortSignal.timeout(YOUTUBE_REQUEST_TIMEOUT_MS),
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/126 Safari/537.36",
  };
}

function selectCaptionLanguage(languages: CaptionTrackInfo[]) {
  return (
    languages.find(
      (language) =>
        language.languageCode.toLowerCase().startsWith("vi") && !language.isAutoGenerated,
    ) ??
    languages.find((language) => language.languageCode.toLowerCase().startsWith("vi")) ??
    languages.find((language) => !language.isAutoGenerated) ??
    languages[0]
  );
}

function isYoutubeVideoId(value: string | null | undefined): value is string {
  return typeof value === "string" && /^[a-zA-Z0-9_-]{11}$/.test(value);
}

function toSettingsRecord(settings: unknown): Record<string, unknown> | null {
  return typeof settings === "object" && settings !== null && !Array.isArray(settings)
    ? (settings as Record<string, unknown>)
    : null;
}

function readNonNegativeNumber(value: unknown, fallback: number) {
  return typeof value === "number" && Number.isFinite(value) && value >= 0
    ? value
    : fallback;
}

function roundTranscriptTime(time: number) {
  return Math.round(time * 1000) / 1000;
}

function isHttpException(error: unknown) {
  return (
    typeof error === "object" &&
    error !== null &&
    "getStatus" in error &&
    typeof (error as { getStatus?: unknown }).getStatus === "function"
  );
}

function getErrorName(error: unknown) {
  return error instanceof Error ? error.constructor.name : "";
}
