HÂ HUY KHOAI (Tông Chú biền)
NGUYỄN HUY DOAN (Chủ bién)
CUNG THỂ ANH - NGUYÉN CAO CƯƠNG - TRÁN MANH CƯƠNG
DOÀN MINH CƯƠNG - TRÀN PHƯƠNG DUNG - SÍ ĐỨC QUANG
LƯU BÁ THÁNG - DẬNG HUNG THÀNG
![](https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-01.jpg?height=1812&width=1839&top_left_y=637&top_left_x=5)

HẦ HUY KHOĂI (Tổng Chủ biên)
NGUYẾN HUY DOAN (Chủ biên)
CUNG THẾ ANH - NGUYẾN CAO CUỜNG - TRẦN MANH CƯƠNG - DOĂN MINH CUỜNG TRẦN PHUƠNG DUNG - Sİ DÚC QUANG - LUU BẢ THẢNG - ĐẬNG HUNG THÂNG

\begin{figure}
\includegraphics[alt={},max width=\textwidth]{https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-02.jpg?height=800&width=1314&top_left_y=734&top_left_x=260}
\captionsetup{labelformat=empty}
\caption{VOI CUÔC SONG}
\end{figure}

\section*{AUGNG DÂN SỨ DUNG SAGH}
\begin{itemize}
\item[1.] Mỗi bài học được thiết kể gồm:
\begin{itemize}
\item[-] Phần Mở đẩu: Thường là một bải toán hay một tính huống có liên quan đến nội dung mới của bải học.
\item[-] Phận Hình thành kiến thức mới: Gồm các hoạt động Tỉm tời - Khám phá ( ) và Đọc hiệu - Nghe hiều (1, ) củng với Chứ ý hay Nhận xét.
\item[-] Kiến thức trọng tâm được đặt trong khung mảu vàng.
\item[-] Câu hỏi ( ) giúp đánh giá kết quả sau hoạt động Đọc hiểu - Nghe hiểu.
\item[-] Phần Luyện tập và củng có: Gồm Vi dư, Luyện tập, Thực hành để hình thảnh và phát triển các kĩ năng gấn với kiến thức mới vừa học.
\item[-] Phần Vận dụng: Gồm các hoạt động Vận dụng, Tranh luận ( \(13^{1}\) ) và Thử thách nhỏ ( ) để giải quyết các tình huống, vấn đề trong thực tiến và mở rộng kiến thức.
\end{itemize}
\item[2.] Các em sē được đồng hảnh với anh Pi, các bạn Tròn, Vuông trong các bải học để việc học hấp dẫn hơn nhé.
![](https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-03.jpg?height=394&width=1457&top_left_y=1289&top_left_x=262)
\item[3.] Các em có thể tham khảo thêm mục Em có biết? để mở rộng hiều biết của minh. Cuối sách là Bàng tra cứu thuật ngữ và Bàng giài thích thuật ngữ.
\end{itemize}
![](https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-03.jpg?height=158&width=978&top_left_y=2215&top_left_x=452)

Các em học sinh yêu quý!
Trên tay các em là cuốn sách TOÁN 7 (tập một) bộ sách giáo khoa "Kết nối tri thức với cuộc sông" của Nhà xuất bản Giáo dục Việt Nam.
Bộ sách TOÁN 7 gồm hai tập, được biên soạn theo định hướng phát triển phẩm chất và năng lực cho học sinh.

Với thông điệp "Kết nối tri thức với cuộc sống", các kiến thức trong sách sẽ đến với các em một cách tự nhiên, bắt nguổn từ thực tế đồi sống và giúp các em biết cách giải quyết những vấn để đặt ra trong cuộc sông.

Thông điệp đó còn nhắc nhở các em thực hiện tốt lời Bác Hố dạy: "Học đi đôi với hành". Muốn làm được điều đó, các em vửa phải mở mang, củng cố kiến thức; vừa phải rèn luyện, náng cao kĩ năng. Kiến thức và kī năng là hai nhân tố quan trọng để các em phát triển năng lực của mình.
Với cách thể hiện phong phủ và lôi cuốn, hình thức trình bày hấp dẫn và thân thiện, TOÁN 7 sẽ giúp các em học Toán được dể dàng. TOÁN 7 còn là người bạn đổng hành cùng các em khám phả vẻ dẹp của Toán học, qua đó các em ngày càng yêu Toán hơn.

Chúc các em học tập chăm chỉ và thành công!

\section*{MUC}

TRANG

TRANG

Chương I. số HỮU TỈ

\begin{tabular}{|l|l|}
\hline Bài 1. Tập hợp các só hữu tỉ & 5 \\
\hline Bài 2. Cọng, trü, nhân, chia sô hưu ti & 10 \\
\hline Luyên tập chung & 14 \\
\hline Bài 3. Luy thứa với só mũ tự nhiên của môt số hừu tị & 16 \\
\hline Bài 4. Thứ tự thực hiện các phép tinh. Quy tắc chuyén vế & 20 \\
\hline Luyęn tập chung & 23 \\
\hline Bài taph cuôi chưng I & 25 \\
\hline
\end{tabular}

Chương IV. TAM GIÁC BẦNG NHAU

\begin{tabular}{|l|l|}
\hline Bài 12. Tóng các góc trong một tam gác & 60 \\
\hline Bài 13. Hai tam giác bäng nhau. Truding hop bang nhau thu nhat cua tam giac & 63 \\
\hline Luyện tấp chung & 63 \\
\hline Bai 14. Trương hợp báng nhau thư hai va thứ ba cua tam giác & 70 \\
\hline Luyént tap chung & 74 \\
\hline Bài 15. Các truóng hop băng nhau cua tam giác vuông & 75 \\
\hline Bài 16. Tam giác can. Duoing trung truc cua doan thang & 80 \\
\hline Luyéntâp chung & 85 \\
\hline Bäi täp cuói chưng IV & 87 \\
\hline
\end{tabular}

Chương II. Số THỰC

\begin{tabular}{|l|l|}
\hline Bài 5. Làm quen voi só thấp phân vô han tuan hoán & 26 \\
\hline Bai 6. Só vó ti. Cán bać hai só hoc & 79 \\
\hline Bài 7. Tạp hợp các só thưc & 33 \\
\hline Luyên tập chung & 37 \\
\hline Bài tập cuói chương II & 39 \\
\hline
\end{tabular}

Chương V. THU THẬP VÀ BIỂU DIỂN DỮ LIỆU

\begin{tabular}{|l|l|}
\hline Bài 17. Thur thập và phán loai dú liệu & 85 \\
\hline Bài 18. Biéu do hinh quat tròn & 93 \\
\hline Bài 19. Biếu dó doán tháng & 100 \\
\hline Luyện tập chung & 106 \\
\hline Bai táp cuni churing V & 108 \\
\hline
\end{tabular}

Chương III. GÓC VÀ DƯỜNG THẦNG SONG SONG

\begin{tabular}{|l|l|}
\hline Bài 8. Góc ó vị tri đặc biệt. Tia phấn giác của một góc & 40 \\
\hline Bài 9. Hai during thãng song song va dẫu hiệu nhận biết & 46 \\
\hline Luyên tập chung & 50 \\
\hline Bài 10. Tiên de Euclid. Tinh chát của hai dưóng thang song song & 51 \\
\hline Bài 11. Dienh li và chuing minh dịnh li & 55 \\
\hline Luyęę tập chung & 58 \\
\hline Bài tập cuối chương III & 59 \\
\hline
\end{tabular}

HOẠT ĐỘNG THỰC HÀNH TRẢI NGHIỆM

\begin{tabular}{|l|l|}
\hline Ve hình đơn giản vờ phán mém GeoGebra & 110 \\
\hline Dần số vả cơ cău dấn số Việt Nam & 115 \\
\hline
\end{tabular}

\begin{tabular}{|l|l|}
\hline BANG TRA CUU THUAT NGÜ & 118 \\
\hline BANGGLAA THICH THUAT NGU & 119 \\
\hline
\end{tabular}

\section*{Chương 1}

\section*{SỐ HÜU TÍ}

Hệ sinh thái trên Trát Dất đang dán bị phá hừ. Cứ sau ba giáy, thé giới mát diện tích rững du dê che phù một sân bóng đá. Trong thé ki qua, hơn \(\frac{1}{2}\) vưng dất ngập nước bịphá hừ; khoảng 50\% rạn san hồ đã biến mát và có thé tói hon 90\% ran san hô sé biến mất vào nằm 2050, ngay cả khi sự nóng lên toàn cáu được giới hạn ở mức tâng 1,5°C.

Mất hệ sinh thái sê gây ra hiệu ứng nhả kinh, khiến Trái Đất ngày càng nóng lên, từ đó sê qây ra các thầm hoạ thiến nhiên thâm khốc.
(Theo Reducdo cita Lien Hipp Quóc nhain ngby Min truoing thégial 5-5-2021)

\section*{Bài 1 TẬP HỢp các só hữu ti}

\begin{tabular}{|l|}
\hline Khái niệm, thuật ngữ \\
\hline Só hữu tỉ \\
\hline
\end{tabular}

Kiến thức, kĩ năng
\begin{itemize}
\item[*] Nhận biết số hữu tỉ, tập hợp các số hữu tỉ Q, số đôi của số hữu tỉ, thứ tư trong tập hợp các số hữu tỉ.
\item[-] Biéu diền só hữu ti trên trục số.
\item[-] So sanh hai só hữu tỉ.
\end{itemize}

Chỉ só WHtR (Waist to Height Ratio) của một người trưởng thành, được tính bằng tỉ số giữa số do vòng bụng và số do chiểu cao (cũng một dơn vị do). Chỉ số này được coi là một công cụ do lường sức khoê hừu ích vi có thể dự báo được các nguy cơ béo phì, mắc bệnh tim mạch, .... Bảng bên cho biết nguy cơ thừa cân, béo phì của một người đàn ông trưởng thảnh dựa vào chỉ số WHtR.

\begin{tabular}{|l|l|}
\hline Gáy & Chỉ số WHtR nhỏ hơn hoặc bằng 0,42 \\
\hline Tót & Chỉ số WHIR lốn hơn 0,42 và nhỏ hơn hoặc bằng 0,52 \\
\hline Hơi béo & Chỉ số WHtR lớn hơn 0,52 và nhỗ hơn hoặc bằng 0,57 \\
\hline Thừa cận & Chỉ số WHtR lón hơn 0,57 và nhỏ hơn hoặc bằng 0,63 \\
\hline Béo phi & Chil só WHtR lón hon 0,63 \\
\hline
\end{tabular}
(Theo hospimedica.com)

Öng An cao 180 cm, vòng bung 108 cm.
Öng Chung cao 160 cm, vòng bụng 70 cm.
Theo em, nếu tinh theo chỉ số WHtR, sức khoẻ của ông An hay ông Chung tốt hơn?

\begin{figure}
\includegraphics[alt={},max width=\textwidth]{https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-07.jpg?height=375&width=386&top_left_y=145&top_left_x=863}
\captionsetup{labelformat=empty}
\caption{Ong An}
\end{figure}

\begin{figure}
\includegraphics[alt={},max width=\textwidth]{https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-07.jpg?height=356&width=396&top_left_y=164&top_left_x=1252}
\captionsetup{labelformat=empty}
\caption{Ong Chung}
\end{figure}

\section*{1 KHÁI NIỆM SỐ HỮU TỈ VÀ BIỂU DIỄN SỐ HỮU TỈ TRÊN TRỤC SỐ}

Şố hữu tỉ là gì?
HD1 Tính chỉ số WHtR của ông An và ông Chung.
HD2 Ta có thể viết \(1,5=\frac{3}{2}=\frac{6}{4}=\frac{9}{6}=\ldots\).
Tương tự, em hāy viết ba phân số bằng nhau và bằng:
a) -2,5;
b) \(2 \frac{3}{4}\).

Các phân số bằng nhau là các cách viết khác nhau của củng một số, số đó gọi là số hừu tỉ. Như vậy, chỉ số WHtR của ông An, ông Chung và các số cho trong HD2 là các số hữu tỉ.

Số hữu tỉ là số viết được dưới dạng phán số \(\frac{a}{b}\) với \(a, b \in \mathbb{Z}, b \neq 0\).
Tập hợp các số hữu tỉ được kí hiệu là Q.
Chú ý. Môi số hữu tỉ đều có một só đối. Só đối của số hữu tỉ \(\frac{a}{b}\) là số hữu tỉ \(-\frac{a}{b}\).
Vi du 1 Các số -7; 0.6; -1,2; \(1 \frac{4}{5}\) có là só hữu tỉ khóng? Vì sao?
Giải. Các số \(-7 ; 0,6 ;-1,2 ; 1 \frac{4}{5}\) là các số hữu tỉ vì chúng đểu viết được dưới dạng phân số:
\[
-7=\frac{-7}{1} ; \quad 0,6=\frac{6}{10} ; \quad-1,2=\frac{-12}{10} ; \quad 1 \frac{4}{5}=\frac{9}{5} .
\]

Luyên tập 1 Giải thích vì sao các số \(8 ;-3,3 ; 3 \frac{2}{3}\) đều là các số hữu tỉ. Tìm số đối của mỗi số đó.
Nhận xét. Vì các số thập phân đã biết đều viết được dưới dạng phân số thập phân nên chúng đểu là các số hữu tỉ. Tương tự, số nguyên, hôn số cũng là các số hữu tỉ.

Cách biểu diễn số hữu tỉ trên trục số
Ta đã biết cách biểu diễn các số nguyễn trên trục số. Chẳng hạn, Hình 1.1 cho ta hình ảnh các số nguyên \(-2 ;-1 ; 1\) và 2 được biểu diển trên trục số.

\begin{figure}
\includegraphics[alt={},max width=\textwidth]{https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-07.jpg?height=102&width=511&top_left_y=2241&top_left_x=1193}
\captionsetup{labelformat=empty}
\caption{Hinh 1.7}
\end{figure}
- Tương tự số nguyên, ta có thể biểu diễn các số hữu tỉ trên trục số. Chẳng hạn, để biểu diễn số hữu tỉ \(\frac{3}{2}\) ta làm như sau:
- Chia doạn thẩng don vị (chẩng hạn doạn từ 0 đến 1) thảnh hai doạn bằng nhau, lấy một đoạn làm đơn vị mới (đơn vị mới bằng \(\frac{1}{2}\) đơn vị cũ) (H.1.2a).
- Số hữu tỉ \(\frac{3}{2}\) được biểu diễn bỏi điểm \(M\) (nằm sau góc \(O\) ) và cách \(O\) một đoạn bằng 3 đơn vị mói (H.1.2b).
Tương tự, số hữu tỉ \(-\frac{3}{2}\) được biểu diễn bởi điểm \(N\) (nằm trước góc \(O\) ) và cách \(O\) một đoạn bằng 3 đón vị mới (H.1.3). Do đó \(O M=O N\).
- Số hữu tỉ \(\frac{3}{2}=1,5\) nên 1,5 cũng được biểu diễn bởi
![](https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-08.jpg?height=132&width=581&top_left_y=262&top_left_x=1123)

\begin{figure}
\includegraphics[alt={},max width=\textwidth]{https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-08.jpg?height=124&width=581&top_left_y=471&top_left_x=1123}
\captionsetup{labelformat=empty}
\caption{Hinh 1.2}
\end{figure}

\begin{figure}
\includegraphics[alt={},max width=\textwidth]{https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-08.jpg?height=138&width=543&top_left_y=963&top_left_x=1161}
\captionsetup{labelformat=empty}
\caption{Hinh 1.3}
\end{figure}
điểm \(M\);
Số hữu tỉ \(-\frac{3}{2}=-\frac{6}{4}\) nên \(-\frac{6}{4}\) cũng được biển diến bởi điểm \(N(H .1 .3)\).
- Trên trục số, điểm biểu diến số hữu tỉ a được goì là điểm a.

Mối điểm \(A, B, C\) trên trục số Hình 1.4 biểu diễn số hữu tỉ nào?

\begin{figure}
\includegraphics[alt={},max width=\textwidth]{https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-08.jpg?height=121&width=956&top_left_y=1585&top_left_x=437}
\captionsetup{labelformat=empty}
\caption{Hinh 1.4}
\end{figure}

Luyện tập 2
Biểu diễn các só hữu tỉ \(\frac{5}{4}\) và \(\frac{-5}{4}\) trên trục só.
Nhận xét. Trên trục số, hai điểm biểu diễn của hai số hữu tỉ đối nhau a và -a nằm về hai phía khác nhau so với điểm \(O\) và có cùng khoảng

\begin{figure}
\includegraphics[alt={},max width=\textwidth]{https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-08.jpg?height=94&width=466&top_left_y=1998&top_left_x=1210}
\captionsetup{labelformat=empty}
\caption{Hinh 1.5}
\end{figure}
cách đến \(O(\mathrm{H} .1 .5)\).

\section*{2 THỨ TỰ TRONG TẬP HỢP CẬC SỐ HỮU TỈ}

Thứ tự trong tập hợp các số hữu tí
HD3 Viết các số hữu tỉ sau dưới dạng phân số rổi so sánh:
a) -1,5 và \(\frac{5}{2}\);
b) -0,375 và \(-\frac{5}{8}\).

HD4 Biểu diễn hai số hữu tỉ -1,5 và \(\frac{5}{2}\) trên trục số. Em hãy cho biết điểm -1,5 nằm trước hay nằm sau điểm \(\frac{5}{2}\) trên trục số.
\begin{itemize}
\item[-] Ta có thể so sánh hai số hữu tỉ bất ki bằng cách viết chúng dưới dạng phán số rồi so sánh hai phân số đó.
\item[-] Với hai số hữu tỉ \(a, b\) bất ki, ta luôn có hoặc \(a=b\) hoặc \(a<b\) hoặc \(a>b\).
\end{itemize}

Cho ba số hữu tỉ \(a, b, c\). Nếu \(a<b\) và \(b<c\) thì \(a<c\) (tính chất bặc cấu).
\begin{itemize}
\item[-] Trên trục số, nếu \(a<b\) thì điểm a nằm trước diểm \(b\).
\end{itemize}

Chú ý. Trên trục số, các điểm nằm trước góc O biểu diến số hữu tỉ âm (tức số hữu tỉ nhỏ hơn 0); các điểm nằm sau gốc Obiểu diễn số hữu tỉ dương (tức số hữu tỉ lớn hơn 0). Số o không là số hữu tỉ dương, cũng không là số hữu tỉ âm.

Vi du 2 So sánh 0,7 và \(\frac{6}{5}\). Từ đó cho biết điểm 0,7 nằm trước hay nằm sau điểm \(\frac{6}{5}\) trên trục só?

Giải. Ta có \(0,7=\frac{7}{10}\) và \(\frac{6}{5}=\frac{12}{10}\). Vì \(\frac{7}{10}<\frac{12}{10}\) nên \(0,7<\frac{6}{5}\).
Do đó điểm 0,7 nằm trước điểm \(\frac{6}{5}\) trên trục số (H.1.6).
![](https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-09.jpg?height=153&width=1031&top_left_y=1653&top_left_x=362)

Nhận xét. Ta có thể sử dụng tinh chất bắc cắu để so sánh 0,7 và \(\frac{6}{5}\) bằng cách như sau: Vì \(0,7<1\) và \(1<\frac{6}{5}\) nèn \(0,7<\frac{6}{5}\).

Luyện tập 3 Sấp xểp các số hữu tỉ sau theo thứ tự từ bé đến lớn.
\[
5 \frac{1}{4} ;-2 ; 3,125 ;-\frac{3}{2} .
\]

Vân dung
Em hāy giải bài toán mở đầu.

\section*{BÀI TẬP}
\begin{itemize}
\item[1.1.] Khẩng định nào sau đây là đúng?
a) \(0,25 \in \mathbb{Q}\);
b) \(-\frac{6}{7} \in \mathbb{Q}\);
c) -235 £ Q.
\item[1.2.] Tìm số đối của các số hữu tỉ sau:
a) \(-0,75\);
b) \(6 \frac{1}{5}\).
\item[1.3.] Các điểm \(A, B, C, D(H .1 .7)\) biểu diễn những số hữu tỉ nào?

\begin{figure}
\includegraphics[alt={},max width=\textwidth]{https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-10.jpg?height=162&width=986&top_left_y=673&top_left_x=424}
\captionsetup{labelformat=empty}
\caption{Hinh 1.7}
\end{figure}
\item[1.4.] a) Trong các phân số sau, những phân số nào biếu diễn số hữu tỉ -0,625?
\[
\frac{5}{-8} ; \quad \frac{10}{16} ; \quad \frac{20}{-32} ; \quad \frac{-10}{16} ; \quad \frac{-25}{40} ; \quad \frac{35}{-48} .
\]
\item[] Nếu hai số hữu tỉ dược viết dưới dạng số thập phân thì ta so sánh trực tiếp, không cẩn đưa về dạng phân số.
\item[1.5.] So sánh:
a) -2,5 và -2,125;
b) \(-\frac{1}{10000}\) và \(\frac{1}{23456}\).
\item[1.6.] Tuổi thọ trung bình dự kiến của những người sinh năm 2019 ổ một số quốc gia được cho trong bảng sau:

\begin{tabular}{|l|l|l|l|l|l|}
\hline Quóc gia & Australia & Pháp & Tây Ban Nha & Anh & Mĩ \\
\hline Tuổi thọ trung binh dự kiến & 83 & 82,5 & \(83 \frac{1}{5}\) & \(81 \frac{2}{5}\) & \(78 \frac{1}{2}\) \\
\hline
\end{tabular}
(Theo Báo cáo của Tố chức Y tế Thế giói, 2020) Sấp xếp các quốc gia theo tuổi thọ trung bình dự kiến từ nhỏ đến lớn.
\end{itemize}

\section*{Bài 2}

\section*{CỘNG, TRỪ, NHÂN, CHIA SỐ HÜU Tİ}

Kiến thức, kĩ năng
\begin{itemize}
\item[*] Thực hiện các phép tinh cộng, trử, nhần, chia trong Q.
\item[-] Vận dụng các tính chất của các phép toán và quy tấc dấu ngoặc để tính viết, tính nhẩm, tính nhanh một cách hợp lí.
\item[-] Giải quyết một số bài toán thực tế dùng só hữu tỉ.
\end{itemize}

Giả sử một khinh khí cầu bay lên từ mặt đất theo chiểu thẳng đứng với vận tốc 0,8 m/s trong 50 giây. Sau đó nó giảm dần độ cao với vận tốc \(\frac{5}{9} \mathrm{~m} / \mathrm{s}\). Hỏi sau 27 giây kể từ khi hạ độ cao, khinh khí cấu cách mặt đất bao nhiều mét?
![](https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-11.jpg?height=392&width=386&top_left_y=596&top_left_x=1342)

\section*{1 CỘNG VÀ TRỪ HAI SỐ HỮU TỈ}

Cách cộng và trử hai số hữu tỉ
HD1 Nhầc lại quy tắc cộng và trừ hai phân số rói thực hiện phép tinh:
a) \(\frac{-7}{8}+\frac{5}{12}\);
b) \(\frac{-5}{7}-\frac{8}{21}\).

HD2 Viết các hỗn số và số thập phân trong phép tính sau dưới dạng phân số rồi thực hiện phép tinh:
a) \(0,25+1 \frac{5}{12}\);
b) \(-1,4-\frac{3}{5}\)

Mối số hữu tỉ đều viết được dưới dạng phán số với mẫu dương.
![](https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-11.jpg?height=166&width=166&top_left_y=1491&top_left_x=1474)

Ta có thể cộng, trừ hai số hữu tỉ bằng cách viết chúng dưới dạng phân số rôi áp dụng quy tắc cộng, trử phân số.

Vidu 1 Tính: a) \(\frac{2}{-3}+2,5+\frac{1}{3}+1 \frac{1}{2}\); b) \(-0,5+\frac{2}{3}+\frac{1}{2}\); c) \((-9,15)+8,09\).
Giải. a) \(\frac{2}{-3}+2,5+\frac{1}{3}+1 \frac{1}{2}\)
Phép cộng số hữu tỉ cũng có tinh chát giao hoán, kết hợp giống
\(=\frac{-2}{3}+\frac{5}{2}+\frac{1}{3}+\frac{3}{2} \quad-\) viết số hữu tỉ dưới đạng phân số có mấu dương phép cộng phân số.
\(=\frac{-2}{3}+\frac{1}{3}+\frac{5}{2}+\frac{3}{2}-\) tính chát giao hoán
![](https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-11.jpg?height=177&width=198&top_left_y=2222&top_left_x=1474)
\(=\left(\frac{-2}{3}+\frac{1}{3}\right)+\left(\frac{5}{2}+\frac{3}{2}\right) \quad-\) tính chát kết hợp
\(=\frac{-1}{3}+4=\frac{11}{3}\) :
\begin{itemize}
\item[b)] \(-0,5+\frac{2}{3}+\frac{1}{2}\)
\(=\frac{-1}{2}+\frac{2}{3}+\frac{1}{2} \quad-\) viết số hữu tỉ dười dạng phân só
\(=\left(\frac{-1}{2}+\frac{1}{2}\right)+\frac{2}{3} \quad-\) tính chắt giao hoán, kết hợp
\(=0+\frac{2}{3}=\frac{2}{3}\); - cộng với só 0
\item[c)] \((-9,15)+8,09=-(9,15-8,09)=-1,06\).
\end{itemize}

Hai số dối nhau luôn có tổng bằng 0:
\[
a+(-a)=0 .
\]
![](https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-12.jpg?height=185&width=215&top_left_y=618&top_left_x=1333)

Chú ý. Nếu hai số hữu tỉ đểu được cho dưới dạng số thập phân thì ta áp dụng quy tắc cộng và trừ đối với số thập phân.

Luyền tập 1 Tinh:
a) \((-7)-\left(-\frac{5}{8}\right)\);
b) \(-21,25+13,3\).

Nhận xét. Trong tập các số hữu tỉ Q, ta cũng có quy tắc dấu ngoặc tương tự như trong tập các số nguyên \(\mathbb{Z}\).
Vidu 2 Tinh: \(\frac{8}{9}-\left[\frac{7}{4}-\left(\frac{3}{4}-\frac{2}{3}\right)\right]\).

Giải. \(\frac{8}{9}-\left[\frac{7}{4}-\left(\frac{3}{4}-\frac{2}{3}\right)\right]=\frac{8}{9}-\frac{7}{4}+\left(\frac{3}{4}-\frac{2}{3}\right)\)
\(=\frac{8}{9}-\frac{7}{4}+\frac{3}{4}-\frac{2}{3}\)
\(=\left(\frac{8}{9}-\frac{2}{3}\right)-\left(\frac{7}{4}-\frac{3}{4}\right)\)
\(=\left(\frac{8}{9}-\frac{6}{9}\right)-1=\frac{2}{9}-1=-\frac{7}{9}\).
- bỏ dẫu ngoác có dău "=" dăng trước dắu ngoặc vuông
- bỏ dấu ngoặc có dấu "+" dằng trước
- đặt dấu ngoặc có dấu "-" đầng trước

Chủ ý. Đối với một tổng trong Q, ta có thể đổi chỗ các só hạng, đặt dấu ngoặc để nhóm các số hạng một cách tuỳ ý như các tổng trong \(\mathbb{Z}\).

Luyện tập 2 Bỏ dấu ngoặc rồi tính các tổng sau:
a) \(\frac{9}{10}-\left(\frac{6}{5}-\frac{7}{4}\right)\);
b) \(6,5+[0,75-(8,25-1,75)]\).

Vần dung 1
Khoai tây là thức ăn chính của người châu Ầu và là một món ăn ua thích của người Việt Nam. Trong 100 g khoai tây khô có 11 g nước; 6,6 g protein; 0,3 g chát béo; 75,1 g glucid và các chất khác.
(Theo Vièn Dinh duong Quóc gia)
Em hãy cho biết khối lượng các chất côn lại trong 100 g
![](https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-13.jpg?height=290&width=511&top_left_y=264&top_left_x=1218)
khoai tây khô.

2 NHÂN VÀ CHIA HAI SỔ HỮU TỈ

Cách nhân và chia hai số hữu tỉ
HD3 Viết các hỗn số và số thập phân trong các phép tính sau dưới dạng phân số rồi thực hiện phép tinh:
a) \(0,36 \cdot \frac{-5}{9}\);
b) \(\frac{-7}{6}: 1 \frac{5}{7}\).

Ta có thể nhân, chia hai số hữu tỉ bằng cách viết chúng dưới dạng phân số rởi áp dụng quy tắc nhân, chia phân số.

Vidu 3 Tinh:
a) \(\frac{6}{7} \cdot 0,25\);
b) \(-2,4=\frac{6}{5}\).

Giải.
a) \(\frac{6}{7} \cdot 0,25=\frac{6}{7} \cdot \frac{25}{100}=\frac{150}{700}=\frac{3}{14}\).
b) \(-2,4: \frac{6}{5}=\frac{-24}{10}: \frac{6}{5}=\frac{-24}{10} \cdot \frac{5}{6}=\frac{-120}{60}=-2\).

Luyên táp 3
Tinh:
a) \(\left(-\frac{9}{13}\right) \cdot\left(-\frac{4}{5}\right)\);
b) \(-0,7: \frac{3}{2}\).

Luyên tạp 4
Tính một cách hợp lí: \(\frac{7}{6} \cdot 3 \frac{1}{4}+\frac{7}{6} \cdot(-0,25)\).
![](https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-13.jpg?height=192&width=219&top_left_y=1815&top_left_x=1357)

Chú ý. Nếu hai số hữu tỉ đều được cho dưới dạng số thập phân thì ta có thể áp dụng quy tắc nhân và chia đối với số thập phân, chảng hạn:
\[
\begin{aligned}
& 1,25 \cdot(-4,6)=-(1,25 \cdot 4,6)=-5,75 ; \\
& 7,8:(-0,13)=-(7,8: 0,13)=-60 .
\end{aligned}
\]

Vidu 4
Trờ lại bài toán mở đầu, trong 50 giây đầu, khinh khí cẩu bay lên cách mặt dất là:
\[
0,8 \cdot 50=40(\mathrm{~m}) .
\]
Sau 27 giáy, khinh khí câu giảm độ cao là: \(\frac{5}{9} \cdot 27=15(\mathrm{~m})\).
Vậy sau 27 giây, khinh khí cẩu cách mặt đất là: \(40-15=25(\mathrm{~m})\).

Vân dung 2
Có hai tấm ảnh kích thước 10 cm × 15 cm được in trên giây ảnh kich thước 21,6 cm × 27,9 cm như Hinh 1.8. Nếu cắt ảnh theo dúng kich thước thì diện tích phán giấy ảnh còn lại là bao nhiều?
![](https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-14.jpg?height=592&width=530&top_left_y=567&top_left_x=1174)

BÀI TẬP
\begin{itemize}
\item[1.7.] Tính:
a) \(\frac{-6}{18}+\frac{18}{27}\);
b) 2,5-(- \(\frac{6}{9}\) );
c) \(-0,32 \cdot(-0,875)\);
d) \((-5): 2 \frac{1}{5}\).
\item[1.8.] Tính giá trị của các biểu thức sau:
a) \(\left(8+2 \frac{1}{3}-\frac{3}{5}\right)-(5+0,4)-\left(3 \frac{1}{3}-2\right)\);
b) \(\left(7-\frac{1}{2}-\frac{3}{4}\right):\left(5-\frac{1}{4}-\frac{5}{8}\right)\).
\item[1.9.] Em hāy tìm cách "nối" các số ở những chiếc lá trong Hình 1.9 bằng dấu các phép tính cộng, trừ, nhân, chia và dấu ngoặc để được một biểu thức có giá trị đúng bằng số ổ bông hoa.
\item[1.10.] Tính một cách hợp lí.
\[
0,65 \cdot 78+2 \frac{1}{5} \cdot 2020+0,35 \cdot 78-2,2 \cdot 2020 .
\]
\end{itemize}

\begin{figure}
\includegraphics[alt={},max width=\textwidth]{https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-14.jpg?height=392&width=266&top_left_y=1629&top_left_x=1376}
\captionsetup{labelformat=empty}
\caption{Hinh 1.9}
\end{figure}
\begin{itemize}
\item[1.11.] Ngăn đựng sách của một giá sách trong thư viện dài 120 cm (xem hình bên). Người ta dự định xếp các cuốn sách dày khoảng 2,4 cm vào ngăn này. Hởi ngăn sách đó có thể để được nhiểu nhất bao nhiêu cuốn sách như vậy?
\end{itemize}
![](https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-14.jpg?height=322&width=586&top_left_y=2100&top_left_x=1114)

\section*{LUYỆN TẬP CHUNG}

Ví du 1 Tính một cách hợp lí.
a) \(A=\frac{37}{5}+(-0,7)+\frac{5}{2}+(-4,3)\);
b) \(B=\frac{3}{2} \cdot\left(-\frac{37}{10}\right)+\frac{17}{2} \cdot\left(-\frac{37}{10}\right)\).

Giải
\begin{itemize}
\item[a)]
\[
\begin{aligned}
A=7,4+(-0,7)+2,5+(-4,3) & =(7,4+2,5)+[(-0,7)+(-4,3)] \\
& =9,9+(-5)=4,9 .
\end{aligned}
\]
\item[b)] \(B=\left(\frac{3}{2}+\frac{17}{2}\right) \cdot\left(-\frac{37}{10}\right)=10 \cdot\left(-\frac{37}{10}\right)=-37\).
\end{itemize}

Vidu 2
\begin{itemize}
\item[a)] Biểu diễn các só hữu tỉ 1,75; -1,25 và \(\frac{1}{4}\) trên trục sós
\item[b)] Sấp xếp các số hữu tỉ trên theo thứ tự từ nhỏ đến lớn dựa vào trục số đã vễ.
\end{itemize}

Giải.
\begin{itemize}
\item[a)] Ta viết \(1,75=\frac{7}{4} ;-1,25=\frac{-5}{4}\).
\end{itemize}
Chia đoạn thẳng đơn vị thành bốn đoạn bằng nhau, lấy một đoạn làm đơn vị mới (đơn vị mới bằng \(\frac{1}{4}\) đơn vị cũ). Khi đó các số hữu tỉ 1,\(75 ;-1,25 ; \frac{1}{4}\) được biểu diến như sau:

\begin{figure}
\includegraphics[alt={},max width=\textwidth]{https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-15.jpg?height=202&width=993&top_left_y=1489&top_left_x=473}
\captionsetup{labelformat=empty}
\caption{Hinh 1.10}
\end{figure}
b) Trên trục só Hình 1.10, -1,25 nằm trước \(\frac{1}{4}\) và \(\frac{1}{4}\) nằm trước 1,75.
Do đó \(-1,25<\frac{1}{4}<1,75\).

BÀI TẬP
1.12. So sánh:
a) \(\frac{123}{7}\) và 17,75 ;
b) \(-\frac{65}{9}\) và \(-7,125\).
\begin{itemize}
\item[1.13.] Bảng sau cho biết các điểm đông đặo và điểm sôi của sáu nguyên tố dược gọi là khi hiếm.
\end{itemize}

\begin{tabular}{|l|l|l|}
\hline Khi hiểm & Điểm đông đặc ( \({ }^{\circ} \mathrm{C}\) ) & Điểm sói ( \({ }^{\circ} \mathrm{C}\) ) \\
\hline Argon (A-gon) & -189,2 & -185,7 \\
\hline Helium (Hê-li) & -272,2 & -268,6 \\
\hline Neon (Nê-on) & -248,67 & -245,72 \\
\hline Krypton (Krip-tôn) & -156,6 & -152,3 \\
\hline Radon (Ra-dón) & -71,0 & -61,8 \\
\hline Xenon (Xê-nôn) & -111,9 & -107,1 \\
\hline
\end{tabular}
(Theo britannica.com)
\begin{itemize}
\begin{itemize}
\item[a)] Khí hiếm nào có điểm đông đặc nhỏ hơn điểm đông đặc của Krypton?
\item[b)] Khi hiếm nào có điểm sôi lớn hơn điểm sôi của Argon?
\item[c)] Hãy sắp xếp các khi hiếm theo thứ tự điểm đông đặc tăng dắn;
\item[d)] Hãy sắp xểp các khi hiếm theo thứ tự điểm sôi giảm dẩn.
\end{itemize}
\item[1.14.] Theo Đài khí tượng thuỷ văn tỉnh Lào Cai, ngày 10-01-2021, nhiệt độ thấp nhất tại thị xā Sa Pa là -0,7°C, nhiệt độ tại thành phố Lào Cai khoảng \(9,6^{\circ} \mathrm{C}\). Hổi nhiệt độ tại thănh phố Láo Cai cao hơn nhiệt độ tại thị xā Sa Pa bao nhiều độ C'?
(Theo vietnamplus.vn)
\item[1.15.] Thay môi dấu "?" bằng số thich hợp dể hoàn thiện sơ đổ Hình 1.11, biết số trong mỗi ô ổ hàng trên bằng tích của hai số trong hai ô kê nó ở hàng dưới.
\item[1.16.] Tính giá trị của các biểu thức sau:
\begin{itemize}
\item[a)] \(A=\left(2-\frac{1}{2}-\frac{1}{8}\right):\left(1-\frac{3}{2}-\frac{3}{4}\right)\);
\end{itemize}
\end{itemize}

\begin{figure}
\includegraphics[alt={},max width=\textwidth]{https://cdn.mathpix.com/cropped/bae27421-2e91-4ff2-a9d0-3443e3a0a189-16.jpg?height=466&width=651&top_left_y=1459&top_left_x=1052}
\captionsetup{labelformat=empty}
\caption{Hinh 1.11}
\end{figure}
\begin{itemize}
\begin{itemize}
\item[b)] \(B=5-\frac{1+\frac{1}{3}}{1-\frac{1}{3}}\).
\end{itemize}
\end{itemize}
\begin{itemize}
\item[1.17.] Tính một cách hợp lí: \(1,2 \cdot \frac{15}{4}+\frac{16}{7} \cdot \frac{-85}{8}-1,2 \cdot 5 \frac{3}{4}-\frac{16}{7} \cdot \frac{-71}{8}\).
\end{itemize}